# Generated by Django 4.2.26 on 2025-12-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PregnantWoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('lmp', models.DateField(verbose_name='Last Menstrual Period')),
                ('edd', models.DateField(verbose_name='Expected Delivery Date')),
                ('gravida', models.IntegerField(default=1)),
                ('parity', models.IntegerField(default=0)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(default='Normal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
