# Generated by Django 4.2.26 on 2025-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnantwoman',
            name='risk_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=50),
        ),
    ]
