# Generated by Django 4.2.26 on 2025-12-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.CharField(help_text='Reason for visit', max_length=200),
        ),
    ]
