# Generated by Django 4.2.26 on 2025-12-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_appointment_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregnantwoman',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pregnantwoman',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pregnantwoman',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pregnantwoman',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pregnantwoman',
            name='emergency_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pregnantwoman',
            name='primary_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pregnantwoman',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pregnantwoman',
            name='edd',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='pregnantwoman',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
