# Generated by Django 4.2.26 on 2025-12-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_pregnantwoman_blood_type_pregnantwoman_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnantwoman',
            old_name='emergency_phone',
            new_name='emergency_contact_phone',
        ),
        migrations.RenameField(
            model_name='pregnantwoman',
            old_name='emergency_relationship',
            new_name='emergency_contact_relation',
        ),
    ]
