# Generated by Django 4.2.26 on 2025-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_emergency_phone_pregnantwoman_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
