# Generated by Django 4.2.26 on 2025-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregnantwoman',
            name='gravida',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pregnantwoman',
            name='parity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
