# Generated by Django 4.2.26 on 2025-12-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_discharge_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency Phone Number', max_length=15, null=True),
        ),
    ]
