# Generated by Django 4.2.26 on 2025-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_delivery_blood_group_delivery_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency Contact Name, Relationship & Phone', max_length=255, null=True),
        ),
    ]
