# Generated by Django 4.2.26 on 2025-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_delivery_emergency_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='discharged_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
