# Generated by Django 4.2.26 on 2025-12-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_delivery_admission_date_delivery_discharged_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='discharged_by',
        ),
        migrations.AddField(
            model_name='discharge',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discharge',
            name='discharged_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
