# Generated by Django 4.2.26 on 2025-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_remove_delivery_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Critical', 'Critical'), ('Deceased', 'Deceased')], max_length=20),
        ),
    ]
