# Generated by Django 4.2.26 on 2025-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_discharge_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregnantwoman',
            old_name='edd',
            new_name='expected_due_date',
        ),
        migrations.AlterField(
            model_name='discharge',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Critical', 'Critical'), ('Deceased', 'Deceased')], max_length=50),
        ),
    ]
