# Generated by Django 4.2.26 on 2025-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_rename_edd_pregnantwoman_expected_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='attending_physician',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='baby_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='baby_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
