# Generated by Django 4.2.26 on 2025-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_delivery_attending_physician_delivery_baby_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='edd',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Date of Delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(verbose_name='Actual Delivery Date'),
        ),
    ]
