# Generated by Django 4.2.26 on 2025-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_delivery_edd_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='billing_status',
            field=models.CharField(choices=[('Pending Clearance', 'Pending Clearance'), ('Cleared', 'Cleared'), ('Insurance Pending', 'Insurance Pending')], default='Pending Clearance', max_length=50),
        ),
        migrations.AddField(
            model_name='discharge',
            name='medications',
            field=models.TextField(blank=True, help_text='List prescriptions and medications', null=True),
        ),
    ]
